<?php echo $this->doctype() ?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Orange and Boosted contributors">
    <meta name="generator" content="Hugo 0.78.1">
    <!-- Boosted core CSS -->
    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/media/boosted/css/orange-helvetica.min.css'); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/media/boosted/css/boosted.min.css'); ?>
    <?php echo $this->headScript()->appendFile($this->baseUrl().'/media/js/jquery-3.5.1.min.js'); ?>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>    
  </head>
  <body>
    
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="<?php echo $this->url(
          array(
              'controller' => 'index',
              'action'     => 'index'
          ), 'default', true) ?>">Accueil</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto mb-2 mb-md-0">
        <li class="nav-item active">
          <a class="nav-link" aria-current="page" href="<?php echo $this->url(
          array(
              'controller' => 'album',
              'action'     => 'index'
          ), 'default', true) ?>">Albums</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?php echo $this->url(array(), 'addAlbum') ?>">Ajouter</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-expanded="false">Dropdown</a>
          <ul class="dropdown-menu" aria-labelledby="dropdown01">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control mr-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

<main class="container" style="margin-top:50px">
    <div class="starter-template text-center py-5 px-3">
         <!-- Global notification handling to use call flashMessenger action helper -->
        <?php if(isset($this->message)) :?>
        <div class="notification">

        <?php echo $this->message ;?>

        </div>    
        <?php endif;?>
        <?php echo $this->layout()->content; ?>
    </div>
</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-right mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Album example is &copy; Boosted, but please download and customize it for yourself!</p>
    <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.0/getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>
    <?php echo $this->headScript()->appendFile($this->baseUrl().'/media/boosted/js/boosted.bundle.min.js'); ?>
  </body>
</html>
